[package]
name = "poor-man-etl"
version = "0.1.0"
authors = ["Grzegorz Gierlach <gierlachg@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
rust_decimal = "1.0.2"
inflections = "1.1.1"
csv = "1.1.1"

[dev-dependencies]
tempfile = "3.1.0"
